"""account

Revision ID: 16d3a951bb03
Revises:
Create Date: 2025-09-14 17:21:03.424907

"""  # noqa: INP001

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16d3a951bb03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("account_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=42), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("clearance", sa.Integer(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account")
    # ### end Alembic commands ###
