"""contacts

Revision ID: 3e11026f2ef8
Revises: 57dfe6f8416b
Create Date: 2025-11-15 21:56:02.789551

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3e11026f2ef8"
down_revision = "57dfe6f8416b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("contact_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=25), nullable=True),
        sa.Column("last_name", sa.String(length=25), nullable=True),
        sa.Column("company", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("created_datetime_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("contact_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contact")
    # ### end Alembic commands ###
