"""Email

Revision ID: 4da95be6c0f2
Revises: 22da29189e08
Create Date: 2024-11-09 11:22:45.857649

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4da95be6c0f2"
down_revision = "22da29189e08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=42), nullable=False))
        batch_op.create_unique_constraint("account_email_unique_constraint", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint("account_email_unique_constraint", type_="unique")
        batch_op.drop_column("email")

    # ### end Alembic commands ###
