"""ledger_item_audit_log_entry_account

Revision ID: 57dfe6f8416b
Revises: b5e9e7346780
Create Date: 2025-10-15 10:22:52.592723

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "57dfe6f8416b"
down_revision = "b5e9e7346780"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item_audit_log_entry", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(
            sa.Column(
                "description", sa.String(length=255), server_default="", default="", insert_default="", nullable=False
            )
        )
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "ledger_item_audit_log_entry_account_account_id", "account", ["account_id"], ["account_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item_audit_log_entry", schema=None) as batch_op:
        batch_op.drop_constraint("ledger_item_audit_log_entry_account_account_id", type_="foreignkey")
        batch_op.drop_column("account_id")
        batch_op.drop_column("description")
        batch_op.drop_column("created_datetime_utc")

    # ### end Alembic commands ###
