"""ledger_item_notes_and_category

Revision ID: 87907e0c983e
Revises: 9b871c71bd3e
Create Date: 2025-10-15 10:10:36.998724

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87907e0c983e"
down_revision = "9b871c71bd3e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "private_notes", sa.String(length=255), nullable=False, default="", insert_default="", server_default=""
            )
        )
        batch_op.add_column(sa.Column("category", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ledger_item", schema=None) as batch_op:
        batch_op.drop_column("category")
        batch_op.drop_column("private_notes")

    # ### end Alembic commands ###
