"""finance_start

Revision ID: 9b871c71bd3e
Revises: 16d3a951bb03
Create Date: 2025-10-11 15:45:26.595382

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9b871c71bd3e"
down_revision = "16d3a951bb03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_item",
        sa.Column("ledger_item_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ledger_item_type", sa.Integer(), nullable=False),
        sa.Column("ledger_item_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_datetime_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_account_id"],
            ["account.account_id"],
        ),
        sa.PrimaryKeyConstraint("ledger_item_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_item")
    # ### end Alembic commands ###
