"""ledger_item_audit_log_entry

Revision ID: b5e9e7346780
Revises: 87907e0c983e
Create Date: 2025-10-15 10:16:19.634499

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b5e9e7346780"
down_revision = "87907e0c983e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_item_audit_log_entry",
        sa.Column("ledger_item_audit_log_entry_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ledger_item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ledger_item_id"],
            ["ledger_item.ledger_item_id"],
        ),
        sa.PrimaryKeyConstraint("ledger_item_audit_log_entry_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_item_audit_log_entry")
    # ### end Alembic commands ###
