"""meetings_start

Revision ID: c12437bbdae6
Revises: 3e11026f2ef8
Create Date: 2026-07-05 19:23:59.221016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12437bbdae6'
down_revision = '3e11026f2ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('meeting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meeting_datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('minutes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###
